-- MySQL Script generated by MySQL Workbench
-- Fri Aug 30 16:29:54 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema codigorapidito
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema codigorapidito
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `codigorapidito` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `codigorapidito` ;

-- -----------------------------------------------------
-- Table `codigorapidito`.`estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codigorapidito`.`estudiante` (
  `id` INT NOT NULL,
  `nombre_alumno` TEXT NOT NULL,
  `apellido_alumno` TEXT NOT NULL,
  `edad` INT NOT NULL,
  `numero_telefonico` INT NOT NULL,
  `correo_electronico` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `codigorapidito`.`sucursal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codigorapidito`.`sucursal` (
  `id` INT NOT NULL,
  `nombre_establecimiento` VARCHAR(100) NOT NULL,
  `ubicacion` VARCHAR(269) NOT NULL,
  `numero_telefonico` VARCHAR(15) NOT NULL,
  `correo_electronico` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `codigorapidito`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codigorapidito`.`curso` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(69) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `codigorapidito`.`asignacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codigorapidito`.`asignacion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `curso_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_asignacion_curso1_idx` (`curso_id` ASC) VISIBLE,
  CONSTRAINT `fk_asignacion_curso1`
    FOREIGN KEY (`curso_id`)
    REFERENCES `codigorapidito`.`curso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `codigorapidito`.`inscripcion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codigorapidito`.`inscripcion` (
  `idinscripcion` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `estudiante_id` INT NOT NULL,
  `sucursal_id` INT NOT NULL,
  `asignacion_id` INT NOT NULL,
  PRIMARY KEY (`idinscripcion`),
  INDEX `fk_inscripcion_estudiante_idx` (`estudiante_id` ASC) VISIBLE,
  INDEX `fk_inscripcion_sucursal1_idx` (`sucursal_id` ASC) VISIBLE,
  INDEX `fk_inscripcion_asignacion1_idx` (`asignacion_id` ASC) VISIBLE,
  CONSTRAINT `fk_inscripcion_estudiante`
    FOREIGN KEY (`estudiante_id`)
    REFERENCES `codigorapidito`.`estudiante` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inscripcion_sucursal1`
    FOREIGN KEY (`sucursal_id`)
    REFERENCES `codigorapidito`.`sucursal` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inscripcion_asignacion1`
    FOREIGN KEY (`asignacion_id`)
    REFERENCES `codigorapidito`.`asignacion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `codigorapidito`.`grado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codigorapidito`.`grado` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(69) NOT NULL,
  `curso_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_grado_curso1_idx` (`curso_id` ASC) VISIBLE,
  CONSTRAINT `fk_grado_curso1`
    FOREIGN KEY (`curso_id`)
    REFERENCES `codigorapidito`.`curso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `codigorapidito`.`reporte_nota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codigorapidito`.`reporte_nota` (
  `id` INT NOT NULL,
  `grado_id` INT NOT NULL,
  `estudiante_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_reporte_nota_grado1_idx` (`grado_id` ASC) VISIBLE,
  INDEX `fk_reporte_nota_estudiante1_idx` (`estudiante_id` ASC) VISIBLE,
  CONSTRAINT `fk_reporte_nota_grado1`
    FOREIGN KEY (`grado_id`)
    REFERENCES `codigorapidito`.`grado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reporte_nota_estudiante1`
    FOREIGN KEY (`estudiante_id`)
    REFERENCES `codigorapidito`.`estudiante` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `codigorapidito`.`reporte_estudiantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `codigorapidito`.`reporte_estudiantes` (
  `id` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `sucursal_id` INT NOT NULL,
  `inscripcion_idinscripcion` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_reporte_estudiantes_sucursal1_idx` (`sucursal_id` ASC) VISIBLE,
  INDEX `fk_reporte_estudiantes_inscripcion1_idx` (`inscripcion_idinscripcion` ASC) VISIBLE,
  CONSTRAINT `fk_reporte_estudiantes_sucursal1`
    FOREIGN KEY (`sucursal_id`)
    REFERENCES `codigorapidito`.`sucursal` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reporte_estudiantes_inscripcion1`
    FOREIGN KEY (`inscripcion_idinscripcion`)
    REFERENCES `codigorapidito`.`inscripcion` (`idinscripcion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
